const mainColor = {
  purple: '#9465AB',
  green: '#71ed4e',
  lightPurple: 'rgba(229, 185, 209, 0.5)',
  lightPurple2: 'rgba(148, 101, 171, 0.5)',
  pureWhite: '#ffffff',
  white: '#F4F4F4',
  white1: '#F8F8F8',
  white2: '#E5E5E5',
  black: '#000000',
  black1: '#101010',
  transparentBlack50: 'rgba(0, 0, 0, 0.50)',
  transparentBlack15: 'rgba(0, 0, 0, 0.15)',
  blue: '#0064AD',
  transparentPurpleBlue50: 'rgba(52, 55, 111, 0.5)',
  transparentBlue70: 'rgba(0, 100, 173, 0.70)',
  transparentBlue50: 'rgba(0, 100, 173, 0.50)',
  transparentBlue15: 'rgba(0, 100, 173, 0.15)',
  lightBlue: '#CBECFF',
  lightBlue1: '#CEE5FC',
  lightBlue2: '#EEF6FE',
  lightBlue3: '#EFF8FF',
  orange: '#F96E20',
  red: '#E31E25',
  red1: '#F44336',
  pink: 'rgba(219, 161, 161, 0.3)',
  grey: '#F6F7F8',
  grey1: '#989BA1',
  grey2: '#787C84',
  grey3: '#EFEDED',
  grey4: '#333333',
  grey5: '#F8F8F8',
  transparentGrey: 'rgba(215, 204, 204, 0.3)',
  transparentGrey2: 'rgba(0, 0, 0, 0.15)',
};

export const colors = {
  primary: mainColor.purple,
  secondary: mainColor.blue,
  white: mainColor.pureWhite,
  background: mainColor.pureWhite,
  red: mainColor.red,
  bg: {
    grey: mainColor.grey3,
    lightGrey: mainColor.grey5,
    transparentGrey: mainColor.transparentGrey,
    modal: mainColor.transparentGrey2,
    lightBlue: mainColor.lightBlue1,
    white: mainColor.pureWhite,
  },
  text: {
    white: mainColor.pureWhite,
    black: mainColor.black,
    blue: mainColor.blue,
    transparentBlue: mainColor.transparentBlue70,
    grey: mainColor.grey1,
    grey333: mainColor.grey4,
    placeholder: mainColor.transparentBlack50,
    red: mainColor.red1,
    purpleBlue: mainColor.transparentPurpleBlue50,
  },
  dot: {
    blue: mainColor.blue,
    purple: mainColor.lightPurple,
  },
  button: {
    blue: mainColor.blue,
    lightBlue: mainColor.lightBlue3,
    special: mainColor.lightBlue1,
    disable: mainColor.grey,
    orange: mainColor.orange,
  },
  icon: {
    white: mainColor.pureWhite,
    black: mainColor.black,
    blue: mainColor.blue,
    disable: mainColor.grey2,
  },
  border: {
    blue1: mainColor.blue,
    blue: mainColor.transparentBlue50,
    lightPurple: mainColor.lightPurple2,
    pink: mainColor.pink,
    disable: mainColor.grey1,
    grey: mainColor.transparentGrey2,
    transparentGrey: mainColor.transparentGrey,
  },
  input: {
    background: mainColor.lightBlue2,
  },
  tab: {
    active: mainColor.blue,
    innactive: mainColor.grey1,
  },
  message: {
    success: mainColor.green,
    error: mainColor.red,
  },
};