export const fonts = {
  Nunito: {
    200: 'Nunito-ExtraLight',
    300: 'Nunito-Light',
    400: 'Nunito-Regular',
    600: 'Nunito-SemiBold',
    700: 'Nunito-Bold',
    800: 'Nunito-ExtraBold',
    900: 'Nunito-Black',
    normal: 'Nunito-Regular',
  },
  DM_Sans: {
    400: 'DMSans-Regular',
    500: 'DMSans-Medium',
    700: 'DMSans-Bold',
    normal: 'DMSans-Regular',
  },
  Tahoma: {
    normal: 'TAHOMA',
  },
  OpenSans: {
    300: 'OpenSans-Light',
    400: 'OpenSans-Regular',
    600: 'OpenSans-SemiBold',
    700: 'OpenSans-Bold',
    800: 'OpenSans-ExtraBold',
    900: 'OpenSans-Black',
    normal: 'OpenSans-Regular',
  },
  Work_Sans: {
    100: 'WorkSans-Thin',
    200: 'WorkSans-ExtraLight',
    300: 'WorkSans-Light',
    400: 'WorkSans-Regular',
    500: 'WorkSans-Medium',
    600: 'WorkSans-SemiBold',
    700: 'WorkSans-Bold',
    800: 'WorkSans-ExtraBold',
    900: 'WorkSans-Black',
    normal: 'WorkSans-Regular',
  },
  Poppins: {
    100: 'Poppins-Thin',
    200: 'Poppins-ExtraLight',
    300: 'Poppins-Light',
    400: 'Poppins-Regular',
    500: 'Poppins-Medium',
    600: 'Poppins-SemiBold',
    700: 'Poppins-Bold',
    800: 'Poppins-ExtraBold',
    900: 'Poppins-Black',
    normal: 'Poppins-Regular',
  },
};